root = "."
tmp_dir = "tmp"

[build]
	cmd = "go build -o ./tmp/api-gateway ./services/api-gateway/cmd/main.go"
	bin = "tmp/api-gateway"
	include_ext = ["go", "tpl", "tmpl", "html"]
	exclude_dir = ["tmp"]
	log = "air_build.log"

[log]
	time = true

[misc]
	clean_on_exit = true
	