services:
  postgres:
    image: postgres:16-alpine
    # container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-booking_db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - booking-net

  api-gateway:
    # container_name: api_gateway
    build:
      context: .
      dockerfile: ./services/api-gateway/Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - API_PORT=${API_PORT:-8080}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - booking-net

volumes:
  pgdata:


networks:
  booking-net:
    driver: bridge
